name: Aitra - Run C# Unit Tests

on:
  workflow_run:
    workflows: ["Aitra - Unit Test Generation"]
    types:
      - completed
    branches: [main]

jobs:
  test:
    name: Run .NET Tests
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }} # Only run if test generation was successful

    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{ github.event.workflow_run.head_branch }} # Checkout the PR branch
          fetch-depth: 0

      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: "6.0.x" # Adjust version as needed

      - name: Install dependencies
        run: |
          cd tests
          dotnet restore

      - name: Build
        run: |
          cd tests
          dotnet build --configuration Release --no-restore

      - name: Run tests
        run: |
          cd tests
          dotnet test --no-restore --verbosity normal --logger "trx;LogFileName=test-results.trx" --collect:"XPlat Code Coverage"

      - name: Test Report
        uses: dorny/test-reporter@v1
        if: success() || failure()
        with:
          name: .NET Test Results
          path: tests/**/test-results.trx
          reporter: dotnet-trx
          fail-on-error: true

      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v3
        with:
          directory: tests/
          fail_ci_if_error: true
          flags: unittests
          name: codecov-umbrella
          verbose: true
